/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.c
 #	source generated by 4D Plugin Wizard
 #	Project : Empty Project
 #	author : Francois Marchal
 #	01/07/2004
 #
 # --------------------------------------------------------------------------------*/


#include "4DPluginAPI.h"
#include "4DPlugin.h"

void PluginMain( PA_long32 selector, PA_PluginParameters params )
{
    try
    {
        int32_t pProcNum = selector;
        sLONG_PTR *pResult = (sLONG_PTR *)params->fResult;
        PackagePtr pParams = (PackagePtr)params->fParameters;
        
        CommandDispatcher(pProcNum, pResult, pParams); 
    }
    catch(...)
    {
        
    }
}

void CommandDispatcher (PA_long32 pProcNum, sLONG_PTR *pResult, PackagePtr pParams)
{
    switch(pProcNum)
    {            
        case 1 :
            new_Command1(pResult, pParams);
            break;
    }
}

// ---------------------------------- new theme1 ----------------------------------

void new_Command1(sLONG_PTR *pResult, PackagePtr pParams)
{
    
}

