/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Empty Project
 #	author : Francois Marchal
 #	01/07/2004
 #
 # --------------------------------------------------------------------------------*/



// --- new theme1
void new_Command1(sLONG_PTR *pResult, PackagePtr pParams);